package com.rltx.truck.broker.port.credit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LoginkServiceImp", targetNamespace = "http://www.logink.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface LoginkServiceImp {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String gpstates(
            @WebParam(name = "arg0", partName = "arg0") String arg0);

	/**
	 * 
	 * @param publicInformation
	 * @param authentication
	 * @param security
	 * @param businessInformation
	 * @return returns com.behosoft.edi.logink.credit.wsClient.GenericResult
	 */
	@WebMethod(operationName = "InterfaceName")
	@WebResult(name = "GenericResult", partName = "GenericResult")
	public GenericResult interfaceName(
            @WebParam(name = "Security", targetNamespace = "http://www.logink.org/", header = true, partName = "Security") Security security,
            @WebParam(name = "Authentication", partName = "Authentication") Authentication authentication,
            @WebParam(name = "PublicInformation", partName = "PublicInformation") PublicInformation publicInformation,
            @WebParam(name = "BusinessInformation", partName = "BusinessInformation") String businessInformation);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String nciicCompare(
            @WebParam(name = "arg0", partName = "arg0") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String nciicCheck(
            @WebParam(name = "arg0", partName = "arg0") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getMessage(
            @WebParam(name = "arg0", partName = "arg0") String arg0);

}
