package com.rltx.truck.broker.port.credit;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * LoginkServiceService service = new LoginkServiceService();
 * LoginkServiceImp portType = service.getLoginkServicePort();
 * portType.gpstates(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "LoginkServiceService", targetNamespace = "http://www.logink.org/", wsdlLocation = "http://credit.logink.org/xyzx2/webService/loginkCreditService?wsdl")
public class LoginkServiceService extends Service {

	private final static URL LOGINKSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.rltx.truck.broker.port.credit.LoginkServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.rltx.truck.broker.port.credit.LoginkServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://credit.logink.org/xyzx2/webService/loginkCreditService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://credit.logink.org/xyzx2/webService/loginkCreditService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		LOGINKSERVICESERVICE_WSDL_LOCATION = url;
	}

	public LoginkServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public LoginkServiceService() {
		super(LOGINKSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://www.logink.org/", "LoginkServiceService"));
	}

	/**
	 * 
	 * @return returns LoginkServiceImp
	 */
	@WebEndpoint(name = "LoginkServicePort")
	public LoginkServiceImp getLoginkServicePort() {
		return super.getPort(new QName("http://www.logink.org/",
				"LoginkServicePort"), LoginkServiceImp.class);
	}

}