metricsMySql:
  url: jdbc:mysql://localhost:3306/kingnet?useSSL=false
  user: root
  password:
metricsInfluxDB:
  host: http://127.0.0.1:8086
  username: spark
  password: spark123
  database: sparksource
kafka:
  bootstrap.servers: localhost:9092
  zookeeper.connect: localhost:2181