
@ApiImplicitParams({
@ApiImplicitParam(name = "id", value = "自增ID", required = true, dataType = "Long", paramType = "form"),
@ApiImplicitParam(name = "code", value = "编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "waybillCode", value = "运单编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "actionGroup", value = "业务动作分组，如：行车记录、异常等", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "actionCode", value = "业务动作编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "actionRecordCode", value = "业务动作记录编码（可重复），进行一个业务动作操作所产生的记录编码一致", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "targetObject", value = "要操作的对象", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "targetField", value = "要操作的字段", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "targetFieldValue", value = "操作的字段值", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "description", value = "描述", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "remark", value = "备注", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "disabled", value = "是否禁用", required = true, dataType = "Boolean", paramType = "form"),
@ApiImplicitParam(name = "deleted", value = "是否删除", required = true, dataType = "Boolean", paramType = "form"),
@ApiImplicitParam(name = "moduleCode", value = "操作模块编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "creatorUserCode", value = "创建人编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "creatorUsername", value = "创建人用户名", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "createTime", value = "创建时间", required = true, dataType = "Date", paramType = "form"),
@ApiImplicitParam(name = "updateUserCode", value = "更新人编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "updateUsername", value = "更新人用户名", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "updateTime", value = "更新时间", required = true, dataType = "Date", paramType = "form"),
@ApiImplicitParam(name = "ip", value = "操作者IP", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "operatorLongitude", value = "操作者所处经度", required = true, dataType = "Double", paramType = "form"),
@ApiImplicitParam(name = "operatorLatitude", value = "操作者所处纬度", required = true, dataType = "Double", paramType = "form"),
@ApiImplicitParam(name = "ownerUserCode", value = "所属用户编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "ownerOrgCode", value = "所属公司编码", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "ownerOrgName", value = "所属公司名字", required = true, dataType = "String", paramType = "form"),
@ApiImplicitParam(name = "synchronousId", value = "同步串号", required = true, dataType = "String", paramType = "form"),
})
